# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
formatters:
  enable:
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
